version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./web.yml:/etc/prometheus/web.yml
    ports:
      - "9090:9090"
    

  alertmanager:
    image: prom/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--web.config.file=/etc/alertmanager/web.yml'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./web.yml:/etc/alertmanager/web.yml
    ports:
      - "9093:9093"
   


