global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
  - static_configs:
      - targets:
        - "alertmanager:9093"
    basic_auth:
      username: "admin"
      password: "Saikiran"

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']
